In [1]:
import tensorflow as tf

/Users/r10138/anaconda3/envs/tensorflow35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)


In [2]:
x1 = tf.Variable(42, name="skalar")
x2 = tf.Variable([22,23,24], name="vektor")
x3 = tf.Variable([[0.1, 0.2],[0.3, 0.4]], name="matrix")

In [3]:
# Erzeugt eine 10x10 große Matrix gefüllt mit 0
x4 = tf.Variable(tf.zeros([10,10]))

In [4]:
# Erzeugt eine 3x3 große Matrix gefüllt mit 1
x5 = tf.Variable(tf.ones([3,3]))

In [5]:
init_op = tf.global_variables_initializer()

In [6]:
with tf.Session() as s:
    s.run(init_op)
    print(x4.eval())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
with tf.Session() as s:
    s.run(init_op)
    print(x5.eval())

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
